# ---------------------------------
# Socks5-Over-AES Proxy Configuration
# ---------------------------------

# client:
client.local.port=8080
server.host=127.0.0.1
client.auth.token=jt-token-01

# server:
server.auth.token.list=jt-token-01,jt-token-02
server.key.path=server.key

# common:
server.port=8001
server.cert.path=server.crt