# ---------------------------------
# Socks5-Over-AES Proxy Configuration
# ---------------------------------

server.port=58001

local.port=58080

remote.host=127.0.0.1

auth.token=jintao-secure-token

server.cert.path=./server.crt

server.key.path=./server.key