# ---------------------------------
# Socks5-Over-AES Proxy Configuration
# ---------------------------------

# client:
client.auth.token=jt-token-01

# client services switch
client.socks5.enabled=true
client.http.enabled=false
client.https.enabled=false

# client listen ports
client.local.port=8080
client.http.port=8081
client.https.port=8082

# remote server target
server.host=127.0.0.1

# server:
server.auth.token.list=jt-token-01,jt-token-02
server.key.path=server.key

# common:
server.port=8001
server.cert.path=server.crt

# monitor:
server.monitor.host=127.0.0.1
server.monitor.port=18080
